### ISSUE TITLE
License Code Implementation

### ISSUE THREAD

**Issue by nilsleh** [VectorInstitute/vbll#3]
Dear @jharrison42 and @jwilles ,

I have read your recent paper with great interest since VBBL is both elegant and practical.  We recently released the first version of a Pytorch domain library for UQ called [Lightning-UQ-Box](https://github.com/lightning-uq-box/lightning-uq-box), where we try to implement various UQ methods from different theoretical underpinnings, with the goal of making these methods more accessible to practitioners. Our research domain is Earth Observation data, where we are looking for exactly those kind of methods. Therefore, I wanted to ask what license your code is released under, since I would be interested to include it in the library. 

Cheers, and thank you for the cool work.

**Comment by jwilles** [comment]
Thanks for the interest! We have released it under an MIT license. Looking forward to the integration.
